//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlRockBand3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlRockBand3.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # http://pksage.com/rbndocs/index.php/All_Practice_Sections
        ///
        ///[prc_intro] &quot;Intro&quot;
        ///[prc_intro_a] &quot;Intro a&quot;
        ///[prc_intro_b] &quot;Intro b&quot;
        ///[prc_intro_c] &quot;Intro c&quot;
        ///[prc_intro_d] &quot;Intro d&quot;
        ///[prc_intro_e] &quot;Intro e&quot;
        ///[prc_intro_slow] &quot;Intro slow&quot;
        ///[prc_intro_slow_a] &quot;Intro slow a&quot;
        ///[prc_intro_slow_b] &quot;Intro slow b&quot;
        ///[prc_intro_slow_c] &quot;Intro slow c&quot;
        ///[prc_intro_slow_d] &quot;Intro slow d&quot;
        ///[prc_intro_slow_1] &quot;Intro slow 1&quot;
        ///[prc_intro_fast] &quot;Intro fast&quot;
        ///[prc_intro_fast_a] &quot;Intro fast a&quot;
        ///[prc_intro_fast_b] &quot;Intro fast  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string All_Practice_Sections {
            get {
                return ResourceManager.GetString("All_Practice_Sections", resourceCulture);
            }
        }
    }
}
